language: python

python:
  - 3.9
install:
  - pip install -r requirements.txt

script:
  - coverage -m unittest discover application/tests
  - pylint --exit-zero $(git ls-files '*.py') #check code style
after-success: 
  - coveralls

